version: '3.8'

services:
  # Servidor Jenkins customizado com Docker CLI
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins_server
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

  # Banco de dados relacional PostgreSQL para persistência da API
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: api_db_test
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  # API Node.js apontando para a pasta /api
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: node_api
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: rootpassword
      DB_NAME: api_db_test
    depends_on:
      - db
    networks:
      - app-network

volumes:
  jenkins_data:
  db_data:

networks:
  app-network:
    driver: bridge
